name: Raspberry multi-arch release once

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/raspberry-release-once.yml

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
      pull-requests: write

  release:
    needs: build
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      packages: write
